stages:
  configure_gx:
    cmd: python -m src.gx_context_configuration
    deps:
      - src/gx_context_configuration.py
      - src/splits.py
    params:
      - data
      - split
      - forecast

  validate-data:
    cmd: python -m src.validate_data
    deps:
      - src/validate_data.py
      - src/gx_context_configuration.py
      - gx/expectations
      - gx/validation_definitions
      - gx/checkpoints
      - data/raw
      - data/processed/train.parquet
      - data/processed/validation.parquet
      - data/processed/test.parquet
      - data/processed/origins.parquet
    metrics:
      - reports/validation.json:
          cache: false

  split:
    cmd: python -m src.splits
    deps:
      - data/raw
      - src/splits.py
    params:
      - data
      - split
      - forecast
    outs:
      - data/processed/train.parquet
      - data/processed/validation.parquet
      - data/processed/test.parquet
      - data/processed/origins.parquet
